// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PakXnvvsBcvasqu3U0Ws9GFcvQ1C0os',
    appId: '1:918550397992:web:83d606ed8b9f5d49f8211d',
    messagingSenderId: '918550397992',
    projectId: 'myproject-f93c9',
    authDomain: 'myproject-f93c9.firebaseapp.com',
    storageBucket: 'myproject-f93c9.appspot.com',
    measurementId: 'G-7QX5MHN308',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8p3NGjsC3DYgKojdxfbIVRifZFkzWxuc',
    appId: '1:918550397992:android:a3c51be3027770aef8211d',
    messagingSenderId: '918550397992',
    projectId: 'myproject-f93c9',
    storageBucket: 'myproject-f93c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZwOy4N0RCSxQXid-ek3wwIg_c2EV6E1w',
    appId: '1:918550397992:ios:496e0f1892a1deb8f8211d',
    messagingSenderId: '918550397992',
    projectId: 'myproject-f93c9',
    storageBucket: 'myproject-f93c9.appspot.com',
    iosBundleId: 'com.example.teste1',
  );
}
